main: org.comroid.minecord.MineCord
name: ${project.name}
version: $pluginVersion
author: $userbase
description: $pluginDescription
api-version: $mcVersionMj
depend:
  - Spiroid

commands:
  minecord:
    description: MineCord configuration command
    permission: minecord.admin
    permission-message: "§7[§9Minecord§7] §cYou are missing the permission: §bminecord.admin§c!"
  validate:
    description: Validate your discord account
    permission: minecord.validate
    permission-message: "§7[§9Minecord§7] §cYou are missing the permission: §bminecord.validate§c!"
  discord:
    description: See the discord name of a user
    permission: minecord.discord
    permission-message: "§7[§9Minecord§7] §cYou are missing the permission: §bminecord.discord§c!"
