main: org.comroid.minecord.MineCord
name: ${project.name}
version: $pluginVersion
author: $userbase
description: $pluginDescription
api-version: $mcVersionMj
depend:
  - Spiroid

commands:
  minecord:
    description: MineCord configuration command
    permission: minecord.admin
    permission-message: "§7[§9Minecord§7] §cYou are missing the permission: §bminecord.admin§c!"
